/*
 * File: app/view/AboutPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('kModerate.view.AboutPanel', {
    extend: 'Ext.Container',
    alias: 'widget.AboutPanel',

    config: {
        html: '<div id="aboutPage"> 		<strong>About kModerate</strong> 		<p>kModerate lets you perform moderation actions, on pending moderation/flagged for review entries in your Kaltura account, directly from your mobile device.</p> 		<p>You login to kModerate using your KMC credentials, and kModerate will list all the entries that needs to be moderated.</p> 		<p>Once you select an entry, you are presented with the entry details and have the ability to play the video in order to decide whether to reject or approve the entry.</p> 		<hr /> 		<strong>Technology</strong> 		<p>kModerate is implemented using <a href="http://sencha.com">Sencha Touch</a>, for iOS look & feel, and Kaltura&apos;s <a href="http://www.kaltura.com/api_v3/testme/client-libs.php">JS Client Library</a></p> 		<p>You can add the app to your home screen by tapping the &apos;actions&apos; icon.</p> 		<hr /> 		<strong>Security</strong> 		<p>kModerate performs, by default, all API calls to Kaltura over HTTPS.</p> 		<p>kModerate uses admin KS so it is important to set the Kaltura host URL to HTTPS so your KS and KMC credentials are not compromised.</p> 		<hr /> 		<strong>Confidentiality</strong> 		<p>kModerate does not store any of the credentials that are being passed through the application.</p> 		<p>In fact, all communication is done from your device directly to Kaltura, and the server on which kModerate is hosted does nothing but serve the application files.</p> 	</div>',
        id: 'aboutPanel',
        styleHtmlContent: true,
        title: 'About'
    }

});