/*
 * File: app/view/AppContainer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('kModerate.view.AppContainer', {
    extend: 'Ext.Container',
    alias: 'widget.appcontainer',
    requires: [
        'kModerate.view.About'
    ],

    config: {
        layout: {
            animation: 'pop',
            type: 'card'
        },
        items: [
            {
                xtype: 'navigationview',
                id: 'loginView',
                itemId: 'mynavigationview',
                items: [
                    {
                        xtype: 'formpanel',
                        id: 'loginForm',
                        itemId: 'myformpanel6',
                        title: 'kModerate',
                        items: [
                            {
                                xtype: 'component',
                                hidden: true,
                                html: '<span id="login-error">Login Failed</span>',
                                id: 'login-error-wrapper',
                                styleHtmlContent: true
                            },
                            {
                                xtype: 'fieldset',
                                defaults: {
                                    labelWidth: '35%',
                                    labelAlign: 'left'
                                },
                                instructions: 'Login using your KMC credentials<br />Change the Kaltura Host URL for working with self-hosted edition\'',
                                title: '',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        label: 'Kaltura Host',
                                        name: 'kalturahost',
                                        value: 'https://www.kaltura.com'
                                    },
                                    {
                                        xtype: 'emailfield',
                                        label: 'Email',
                                        name: 'email',
                                        placeHolder: 'email@example.com'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        label: 'Password',
                                        name: 'password'
                                    },
                                    {
                                        xtype: 'togglefield',
                                        itemId: 'mytogglefield',
                                        label: 'Remember',
                                        name: 'toggle'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                id: 'loginButton',
                                text: 'Login'
                            }
                        ]
                    }
                ],
                navigationBar: {
                    items: [
                        {
                            xtype: 'about',
                            cls: 'about',
                            align: 'right'
                        }
                    ]
                }
            },
            {
                xtype: 'navigationview',
                id: 'mainView',
                navigationBar: {
                    items: [
                        {
                            xtype: 'about',
                            cls: 'about',
                            align: 'right'
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'list',
                        id: 'entryList',
                        itemId: 'entryList',
                        itemTpl: [
                            '<div class="entryInList">',
                            '		<div class="left">',
                            '			<img src="http://cdnbakmi.kaltura.com/p/9008/sp/900800/thumbnail/entry_id/{entryId}/width/40/height/30" width="40" height="30" />',
                            '		</div>',
                            '		<div class="right">',
                            '			<strong>{firstName}</strong>',
                            '			<span>{strModerationStatus}</span>',
                            '		</div>',
                            '		<div class="clear"></div>',
                            '	</div>'
                        ],
                        store: 'MyStore',
                        title: 'Videos'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        layout: {
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                id: 'logout',
                                text: 'Logout'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMytogglefieldChange',
                event: 'change',
                delegate: '#mytogglefield'
            }
        ]
    },

    onMytogglefieldChange: function(slider, thumb, newValue, oldValue, options) {
        kModerate.vars.rememberMeChecked = newValue;
    }

});