/*
 * File: app/view/EntryListDetail.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('kModerate.view.EntryListDetail', {
    extend: 'Ext.Container',
    alias: 'widget.EntryListDetail',

    config: {
        id: 'entryListDetail',
        styleHtmlContent: true,
        layout: {
            type: 'fit'
        },
        scrollable: true,
        title: 'Detail',
        tpl: [
            '<div class="entryModerationDetails">',
            '	<p><strong>Name:</strong> {firstName}</p>',
            '	<p><strong>Entry ID:</strong> {entryId}</p>',
            '	<p><strong>Moderation Status:</strong> {strModerationStatus}</p>',
            '	<p><strong>Description:</strong> {description}</p>',
            '	<p><strong>User ID:</strong> {userId}</p>',
            '	<p><strong>Tags:</strong> {tags}</p>',
            '	<p>{playerHTML}</p>',
            '</div>'
        ]
    }

});