/*
 * File: app.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Entry'
    ],
    stores: [
        'MyStore'
    ],
    views: [
        'EntryListDetail',
        'AboutPanel',
        'About',
        'AppContainer'
    ],
    icon: 'icon.png',
    name: 'kModerate',

    controllers: [
        'MainController'
    ],

    launch: function() {
        kModerate.vars = {
            debug: false,
            ks: null,
            host: 'https://www.kaltura.com',
            viewingEntryId: null,
            moderationCurrentAction: null,
            rememberMeChecked: false
        };

        kModerate.myLog = function(msg){
            if (kModerate.vars.debug){
                console.log(msg);
            }
        };

        documentCookies = document.cookie.split(";");
        for (i=0;i<documentCookies.length;i++)
        {
            x=documentCookies[i].substr(0,documentCookies[i].indexOf("="));
            y=documentCookies[i].substr(documentCookies[i].indexOf("=")+1);
            x=x.replace(/^\s+|\s+$/g,"");
            if(x == 'kmoderateLogin')
            {
                kModerate.vars.ks = y;  
            }
        }

        Ext.create('kModerate.view.AppContainer', {fullscreen: true});
    }

});
